version: "3"

services:
  web:
    build:
      context: ./django
      dockerfile: Dockerfile
    volumes:
      - ./django:/app/django
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3307
      - DATABASE_NAME=mydatabase
      - DATABASE_USER=chson
      - DATABASE_PASSWORD=8846
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=4126
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=chson
      - MYSQL_PASSWORD=8846
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3307:3306"

  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    volumes:
      - ./react:/react
    ports:
      - "3000:3000"

volumes:
  mariadb_data:
# networks:
#   my_network:
#     driver: bridge
