
CREATE DATABASE IF NOT EXISTS mydatabase;

USE mydatabase;

CREATE TABLE IF NOT EXISTS user_account (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    nickname VARCHAR(30) NOT NULL,
    profile_image_id INT,
    use_fg TINYINT(1) DEFAULT 1 NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    is_active TINYINT(1) DEFAULT 1 NOT NULL,
    is_staff TINYINT(1) DEFAULT 1 NOT NULL,
    password VARCHAR(128) NOT NULL,
    last_login DATETIME,
    is_superuser TINYINT(1) DEFAULT 1 NOT NULL
);
